stages:
  - deploy

deploy:
  stage: deploy
  script:
    # Install ssh client if not available
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    
    # Start the ssh-agent
    - eval $(ssh-agent -s)
    
    # Add the SSH private key to the ssh-agent
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    
    # Create and set permissions for the ssh directory
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    
    # Disable strict host key checking and use an empty known hosts file
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n\n" > ~/.ssh/config
    
    # Connect to the server and execute deployment commands
    - ssh $SSH_USER@$VM_IPADDRESS "
        hostname && sudo -i &&
        cd /home/msp-repo/frontend &&
        sudo git pull &&
        sudo yarn &&
        sudo yarn generate &&
        pm2 start "yarn start" --name frontend
      "
      
  only:
    - dev2  # Only deploy on changes to the 'dev2' branch