export const appConfig = {
    REACT_APP_GOOGLE_MAPS_API_KEY: process.env.REACT_APP_GOOGLE_MAPS_API_KEY,
    SECRET_KEY: process.env.SECRET_KEY,
    BACKEND_URL: process.env.BACKEND_URL,
    FRONTEND_URL: process.env.FRONTEND_URL,
    FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
    REACT_APP_STRIPE_PAYMENT_KEY: process.env.REACT_APP_STRIPE_PAYMENT_KEY,
    REACT_APP_FREE_TRIAL_ID: process.env.REACT_APP_FREE_TRIAL_ID,
    REACT_APP_SQUARE_APPLICATION_ID: process.env.REACT_APP_SQUARE_APPLICATION_ID,
    REACT_APP_SQUARE_LOCATION_ID: process.env.REACT_APP_SQUARE_LOCATION_ID || ""
}